server:
  port: 8001
spring:
  application:
    name: cloud-payname-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
    prefer-ip-address: true
    instance-id: payment8001  #主机名
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka, http://eureka7001.com:7001/eureka
#mybatis:
##  mapper-locations: classpath:mapper/*.xml
#http://localhost:7001/eureka/
#http://eureka7002.com:7001/eureka,http://eureka7001.com:7002/eureka
#  type-aliases-package: com.atguigu.springcloud.entities

