server:
  port: 8006
spring:
  application:
    name: cloud-zookeeper-payment
  cloud:
    zookeeper:
      connect-string: 192.168.23.131:181
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver