server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:xiachuang/springcloud.git
          search-paths:
            - springcloud-config
      label: master
  rabbitmq:
    host: 192.168.23.131
    port: 5672
    username: guest
    password: guest
eureka:
  instance:
    instance-id: config-center
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka, http://eureka7001.com:7001/eureka
management:
  endpoints:
      web:
        exposure:
          include: bus-refresh
#服务注册eureka