server:
  port: 80
spring:
  application:
    name: consumer-fegin-order
eureka:
  instance:
    instance-id: feginOrder80
    prefer-ip-address: false  #是否把服务注册进注册中心
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7002.com:7002/eureka
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000

#  全局配置
#ribbon:
#  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
#  ReadTimeout: 5000
#  #指的是建立连接后从服务器读取到可用资源所用的时间
#  ConnectTimeout: 5000
logging:
  config:
    at.guigu.springcloud.service.OrdersService: debug


# NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
# NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
# NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试
# NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule